import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/page";
import FirstHero from "@/components/FirstHero/page"
import {
        ClerkProvider,
        SignInButton,
        SignedIn,
        SignedOut,
        UserButton
      } from '@clerk/nextjs'
      import { ConvexClientProvider } from "./ConvexClientProvider";
import SecondHero from "@/components/SecondHero/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <ConvexClientProvider>
     <ClerkProvider>
     <html lang="en">
       <body className="bg-white" >
        <Header/>
         {children}
       </body>
     </html>
   </ClerkProvider>
   </ConvexClientProvider>
  );
}
